@startuml Connection
opt if connection with ReceiverEndpoint
WebSocketAudioReceiver -> WebSocketHub: registerInputSession(userId, session)
WebSocketHub -> UserTimeoutScheduler: cancelStopForUser(userId)
end

opt if connection with StreamerEndpoint:
AudioWebSocketStreamer -> WebSocketHub: registerOutputSession(userId, session)
WebSocketHub -> UserTimeoutScheduler: cancelStopForUser(userId)
end

opt if disconnect with ReceiverEndpoint:
WebSocketAudioReciever -> WebSocketHub: unregisterInputSession(userId)
WebSocketHub -> UserTimeoutScheduler: scheduleStopForUser(userId, port)
opt if no Users left:
UserTimeoutScheduler -> WebSocketHub: stop()
end
end

opt if disconnect with StreamerEndpoint:
AudioWebSocketStreamer -> WebSocketHub: unregisterOutputSession(userId)
WebSocketHub -> UserTimeoutScheduler: scheduleStopForUser(userId, port)
opt if no Users left:
UserTimeoutScheduler -> WebSocketHub: stop()
end
end
@enduml