include 'com.clt.base'
include 'com.clt.xml'
include 'com.clt.script'
include 'com.clt.mac'
include 'com.clt.audio'
include 'ClientInterface'
include 'Diamant'
include 'com.clt.speech'
//include 'SpeechClient'
//include 'TTSClient'
//include 'RecognizerClient'
include 'com.clt.web'
include 'com.clt.webServer'

include 'plugins:DialogOS_MaryTTSPlugin'
include 'plugins:DialogOS_SphinxPlugin'
include 'plugins:DialogOS_LocalAudioPlugin'
include 'plugins:DialogOS_RemoteAudioPlugin'
include 'plugins:DialogOS_FileAudioPlugin'
include 'plugins:DialogOS_RemoteAudioPlugin2'

rootProject.name = "dialogos"


