dependencies {
    implementation project(':com.clt.audio')
    // https://mvnrepository.com/artifact/org.eclipse.jetty/jetty-server
    implementation("org.eclipse.jetty:jetty-server:9.4.57.v20241219")
    // https://mvnrepository.com/artifact/org.eclipse.jetty/jetty-servlet
    implementation("org.eclipse.jetty:jetty-servlet:9.4.57.v20241219")
    // https://mvnrepository.com/artifact/org.eclipse.jetty.websocket/websocket-server
    implementation("org.eclipse.jetty.websocket:websocket-server:9.4.57.v20241219")
    // https://mvnrepository.com/artifact/org.eclipse.jetty.websocket/websocket-api
    implementation("org.eclipse.jetty.websocket:websocket-api:9.4.57.v20241219")
}